server:
  port: 8982
spring:
  application:
    name: API-USERS
  cloud:
    nacos:
      server-addr: 101.35.1.194:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.35.1.194:3306/yingxue?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.maxqaq.dao: debug