server:
  port: 8980
spring:
  application:
    name: API-ADMINS
  cloud:
    nacos:
      server-addr: 101.35.1.194:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.35.1.194:3306/yingxue?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  redis:
    port: 6379
    host: 101.35.1.194
mybatis-plus:
  mapper-locations: classpath:com/maxqaq/mapper/*.xml
logging:
  level:
    com.maxqaq.dao: debug